#Hugo configuration
title = "hahaaas"
baseURL = "https:\/\/hahaaas.ss.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "ss.com"
